"""Electric vehicle manufacturing industry profile placeholder."""

from __future__ import annotations

from procurement_data_generator.modules.shared.industry_profiles.profile_contract import (
    IndustryProfile,
    ProcurementProfile,
    ProductionProfile,
    SharedProfile,
)
from procurement_data_generator.modules.shared.quantity_precision import DECIMAL_QUANTITY_UOMS, INTEGER_QUANTITY_UOMS


EV_MANUFACTURING_PROFILE = IndustryProfile(
    industry_id="ev_manufacturing",
    industry_name="Electric Vehicle Manufacturing",
    industry_description="Catalog and realism hints for EV component procurement and production execution.",
    supported_domains=("procurement", "production"),
    procurement=ProcurementProfile(
        supplier_name_patterns=(
            "{technology} Systems",
            "{component} Manufacturing",
            "{region} Mobility Components",
            "{material} Industrial Supply",
        ),
        component_categories=(
            "Battery Components",
            "Electrical Components",
            "Powertrain Components",
            "Charging Components",
            "Thermal Management",
            "Mechanical Components",
            "Safety Components",
            "Packaging Materials",
            "Maintenance Spares",
        ),
        component_name_patterns=(
            "Lithium Cell Module",
            "Battery Management Controller",
            "Drive Motor Stator",
            "High Voltage Connector",
            "Charging Inlet Assembly",
            "Thermal Cooling Plate",
            "Brake Control Sensor",
            "Protective Packaging Set",
        ),
        component_category_codes=(
            "Battery",
            "Electrical",
            "Mechanical",
            "Packaging",
            "Maintenance",
            "Safety",
            "Electronics",
        ),
        component_material_examples={
            "Battery Components": (
                "Lithium-Ion Cell",
                "Battery Management PCB",
                "Thermal Pad",
                "Copper Busbar",
            ),
            "Drive Components": (
                "Motor Magnet NdFeB",
                "Aluminium Housing",
                "Wiring Harness",
                "Power Connector",
            ),
        },
        component_specification_patterns={
            "Battery Components": ("21700", "Prismatic", "Grade A", "2mm", "HV", "12mm"),
            "Drive Components": ("N52", "Reinforced", "High Voltage", "IP67", "Automotive Grade"),
        },
        component_uom_preferences={
            "Battery Components": ("BatteryPack", "Module", "EA"),
            "Electrical Components": ("EA", "PCS", "Set"),
            "Thermal Management": ("EA", "Liter", "Meter"),
            "Packaging Materials": ("Box", "Pack", "Roll"),
        },
        component_cost_profiles={
            "Battery Components": (150.0, 2500.0),
            "Electrical Components": (12.0, 650.0),
            "Mechanical Components": (8.0, 420.0),
        },
        component_financial_profiles={
            "Battery Components": {
                "unit_price_min": 100.0,
                "unit_price_max": 2500.0,
                "quantity_min": 20.0,
                "quantity_max": 300.0,
                "line_amount_soft_max": 500000.0,
                "high_value_probability": 0.025,
            },
            "Electrical Components": {
                "unit_price_min": 25.0,
                "unit_price_max": 1200.0,
                "quantity_min": 20.0,
                "quantity_max": 500.0,
                "line_amount_soft_max": 350000.0,
                "high_value_probability": 0.012,
            },
            "Powertrain Components": {
                "unit_price_min": 200.0,
                "unit_price_max": 3000.0,
                "quantity_min": 5.0,
                "quantity_max": 150.0,
                "line_amount_soft_max": 500000.0,
                "high_value_probability": 0.02,
            },
            "Thermal Management": {
                "unit_price_min": 20.0,
                "unit_price_max": 800.0,
                "quantity_min": 20.0,
                "quantity_max": 500.0,
                "line_amount_soft_max": 280000.0,
                "high_value_probability": 0.006,
            },
            "Mechanical Components": {
                "unit_price_min": 5.0,
                "unit_price_max": 500.0,
                "quantity_min": 50.0,
                "quantity_max": 1000.0,
                "line_amount_soft_max": 180000.0,
                "high_value_probability": 0.002,
            },
            "Charging Components": {
                "unit_price_min": 50.0,
                "unit_price_max": 1500.0,
                "quantity_min": 10.0,
                "quantity_max": 300.0,
                "line_amount_soft_max": 375000.0,
                "high_value_probability": 0.012,
            },
            "Safety Components": {
                "unit_price_min": 5.0,
                "unit_price_max": 300.0,
                "quantity_min": 50.0,
                "quantity_max": 1000.0,
                "line_amount_soft_max": 160000.0,
                "high_value_probability": 0.002,
            },
            "Packaging Materials": {
                "unit_price_min": 0.5,
                "unit_price_max": 100.0,
                "quantity_min": 100.0,
                "quantity_max": 5000.0,
                "line_amount_soft_max": 90000.0,
                "high_value_probability": 0.0,
            },
            "Maintenance Spares": {
                "unit_price_min": 10.0,
                "unit_price_max": 750.0,
                "quantity_min": 5.0,
                "quantity_max": 200.0,
                "line_amount_soft_max": 120000.0,
                "high_value_probability": 0.002,
            },
        },
        component_category_aliases={
            "battery": "Battery Components",
            "electrical": "Electrical Components",
            "electronics": "Electrical Components",
            "mechanical": "Mechanical Components",
            "packaging": "Packaging Materials",
            "maintenance": "Maintenance Spares",
            "safety": "Safety Components",
            "powertrain": "Powertrain Components",
            "thermal": "Thermal Management",
            "charging": "Charging Components",
        },
        plant_type_names=(
            "EV Assembly Plant",
            "Battery Systems Plant",
            "Component Facility",
            "Powertrain Plant",
        ),
        warehouse_type_names=(
            "Raw Material Warehouse",
            "Quality Hold Warehouse",
            "Rejected Material Warehouse",
            "Maintenance Spares Warehouse",
            "Inbound Warehouse",
            "Packaging Warehouse",
            "Finished Goods Staging Warehouse",
            "Tools and Consumables Warehouse",
            "Safety Stock Warehouse",
        ),
        supplier_component_relationship_rules=(
            "Prefer suppliers certified for the component category.",
            "Battery and high-voltage components should have tighter supplier qualification.",
        ),
    ),
    production=ProductionProfile(
        product_categories=(
            "EV Battery Pack Assembly",
            "Drive Motor Assembly",
            "Power Electronics Control Unit",
            "Charging Module Assembly",
            "Thermal Management Unit",
            "Brake Control Assembly",
            "High Voltage Wiring Harness Assembly",
        ),
        product_name_patterns=(
            "Battery Pack Assembly",
            "Drive Motor Assembly",
            "Power Electronics Controller",
            "Charging Module",
            "Thermal Management Unit",
            "Brake Control Assembly",
            "High Voltage Harness",
        ),
        work_center_names=(
            "Battery Assembly Line",
            "Motor Assembly Cell",
            "Electronics Assembly Station",
            "Thermal Unit Assembly",
            "Final Assembly Line",
            "Calibration Station",
            "End-of-Line Testing",
            "Quality Inspection Station",
        ),
        routing_operation_names=(
            "Material Preparation",
            "Component Assembly",
            "Torque / Fitment",
            "Electrical Calibration",
            "Thermal Calibration",
            "In-Process Inspection",
            "End-of-Line Test",
            "Packaging / Release",
        ),
        product_catalog=(
            {
                "name": "EV Battery Pack Assembly",
                "category": "Battery Pack",
                "product_type": "FinishedGood",
                "uom": "EA",
                "base_cost": 18500,
                "base_hours": 18,
            },
            {
                "name": "Drive Motor Assembly",
                "category": "Drive Unit",
                "product_type": "FinishedGood",
                "uom": "EA",
                "base_cost": 12400,
                "base_hours": 14,
            },
            {
                "name": "Power Electronics Control Unit",
                "category": "Power Electronics",
                "product_type": "SemiFinished",
                "uom": "Unit",
                "base_cost": 7600,
                "base_hours": 9,
            },
            {
                "name": "Charging Module Assembly",
                "category": "Power Electronics",
                "product_type": "FinishedGood",
                "uom": "EA",
                "base_cost": 5200,
                "base_hours": 7,
            },
            {
                "name": "Thermal Management Unit",
                "category": "Thermal Module",
                "product_type": "SemiFinished",
                "uom": "Unit",
                "base_cost": 4100,
                "base_hours": 6,
            },
            {
                "name": "Brake Control Assembly",
                "category": "Chassis Assembly",
                "product_type": "SemiFinished",
                "uom": "EA",
                "base_cost": 3300,
                "base_hours": 5,
            },
            {
                "name": "High Voltage Wiring Harness Assembly",
                "category": "Power Electronics",
                "product_type": "SemiFinished",
                "uom": "Set",
                "base_cost": 2900,
                "base_hours": 4,
            },
        ),
        work_center_catalog=(
            {"name": "Battery Assembly Line", "line_name": "Battery Line A"},
            {"name": "Motor Assembly Cell", "line_name": "Drive Unit Line"},
            {"name": "Electronics Assembly Station", "line_name": "Electronics Line"},
            {"name": "Thermal Unit Assembly", "line_name": "Thermal Line"},
            {"name": "Final Assembly Line", "line_name": "Final Assembly"},
            {"name": "Calibration Station", "line_name": "Calibration"},
            {"name": "End-of-Line Testing", "line_name": "Testing"},
            {"name": "Quality Inspection Station", "line_name": "Quality"},
        ),
        fallback_components=(
            {"ComponentID": 1, "ComponentName": "Battery Cell Module", "UOM": "EA"},
            {"ComponentID": 2, "ComponentName": "Copper Busbar", "UOM": "EA"},
            {"ComponentID": 3, "ComponentName": "Thermal Interface Material", "UOM": "KG"},
            {"ComponentID": 4, "ComponentName": "Power Control PCB", "UOM": "EA"},
            {"ComponentID": 5, "ComponentName": "Cooling Tube", "UOM": "Meter"},
            {"ComponentID": 6, "ComponentName": "Fastener Set", "UOM": "Set"},
            {"ComponentID": 7, "ComponentName": "Insulation Film", "UOM": "Roll"},
            {"ComponentID": 8, "ComponentName": "Current Sensor", "UOM": "EA"},
        ),
        fallback_plants=(
            {"PlantID": 1, "PlantName": "Detroit EV Assembly"},
        ),
        fallback_warehouses=(
            {"WarehouseID": 1, "PlantID": 1, "WarehouseName": "Detroit Raw Material Warehouse"},
        ),
        bom_patterns=(
            "Finished assemblies consume controller, harness, mechanical, and packaging components.",
            "Battery assemblies consume cell modules, busbars, controllers, and safety components.",
        ),
        scrap_yield_profiles={
            "Assembly": (0.0, 2.0),
            "Calibration": (0.0, 1.0),
            "End-of-Line Test": (0.0, 1.5),
        },
        quality_defect_codes=(
            "TorqueDeviation",
            "ElectricalContinuityFailure",
            "ThermalLeak",
            "CalibrationFailure",
            "CosmeticDamage",
            "ConnectorFitmentIssue",
        ),
        rework_reason_codes=(
            "RetorqueRequired",
            "ConnectorReseat",
            "CalibrationRetry",
            "HarnessRoutingCorrection",
        ),
        cost_profiles={
            "LaborRatePerHour": (35.0, 85.0),
            "OverheadPct": (8.0, 22.0),
        },
    ),
    shared=SharedProfile(
        countable_uoms=tuple(sorted(INTEGER_QUANTITY_UOMS)),
        measurable_uoms=tuple(sorted(DECIMAL_QUANTITY_UOMS)),
        default_currency="USD",
        date_scope_notes=("Current generated scenarios remain in calendar year 2025.",),
        realism_notes=(
            "EV names are current demo catalog hints only.",
            "Operating scope lives outside the industry profile layer.",
        ),
    ),
)
