"""Food and snack manufacturing industry profile."""

from __future__ import annotations

from procurement_data_generator.modules.shared.industry_profiles.profile_contract import (
    IndustryProfile,
    ProcurementProfile,
    ProductionProfile,
    SalesProfile,
    SharedProfile,
)
from procurement_data_generator.modules.shared.quantity_precision import DECIMAL_QUANTITY_UOMS, INTEGER_QUANTITY_UOMS


FOOD_MANUFACTURING_PROFILE = IndustryProfile(
    industry_id="food_manufacturing",
    industry_name="Food Manufacturing",
    industry_description="Catalog and realism hints for packaged food and snack manufacturing.",
    supported_domains=("procurement", "production", "sales"),
    procurement=ProcurementProfile(
        supplier_name_patterns=(
            "Ingredient Supplier",
            "Oil Supplier",
            "Seasoning Supplier",
            "Packaging Supplier",
            "Label Supplier",
            "Carton Supplier",
        ),
        component_categories=(
            "Raw Ingredient",
            "Seasoning",
            "Edible Oil",
            "Packaging Film",
            "Carton",
            "Label",
        ),
        component_name_patterns=(
            "Potato Flakes",
            "Corn Flour",
            "Edible Oil",
            "Masala Seasoning",
            "Salt",
            "Packaging Film Roll",
            "Printed Label",
            "Corrugated Carton",
        ),
        component_category_codes=(
            "Raw Ingredient",
            "Raw Ingredients",
            "Seasoning",
            "Seasonings & Spices",
            "Edible Oil",
            "Edible Oils",
            "Packaging Film",
            "Carton",
            "Cartons",
            "Label",
            "Labels",
            "Cleaning Consumables",
            "Food Safety",
        ),
        component_material_examples={
            "Raw Ingredient": ("Potato Flakes", "Corn Flour", "Salt"),
            "Seasoning": ("Masala Seasoning", "Cheese Seasoning", "Chili Seasoning"),
            "Edible Oil": ("Sunflower Oil", "Palmolein Oil", "Rice Bran Oil"),
            "Packaging Film": ("Packaging Film Roll", "Laminated Snack Pouch", "Food Grade Wrapper"),
            "Carton": ("Corrugated Carton", "Outer Shipping Carton", "Display Carton"),
            "Label": ("Printed Label", "Batch Code Label", "Nutrition Label Roll"),
        },
        component_specification_patterns={
            "Raw Ingredient": ("Food Grade", "Low Moisture", "25kg", "Batch Certified"),
            "Seasoning": ("Food Grade", "Fine Powder", "Allergen Declared", "10kg"),
            "Edible Oil": ("Food Grade", "Refined", "Low FFA", "20L"),
            "Packaging Film": ("Food Safe", "Heat Sealable", "Printed", "Micron 60"),
            "Carton": ("Corrugated", "Food Safe", "Printed", "Export Grade"),
            "Label": ("Printed", "Food Contact Safe", "Roll", "Smudge Resistant"),
        },
        component_uom_preferences={
            "Raw Ingredient": ("KG", "Pack"),
            "Seasoning": ("KG", "Pack"),
            "Edible Oil": ("Liter", "Drum"),
            "Packaging Film": ("Roll", "Meter"),
            "Carton": ("EA", "Box"),
            "Label": ("Roll", "EA"),
        },
        component_cost_profiles={
            "Raw Ingredient": (5.0, 80.0),
            "Seasoning": (2.0, 120.0),
            "Edible Oil": (5.0, 90.0),
            "Packaging Film": (5.0, 60.0),
            "Carton": (5.0, 25.0),
            "Label": (5.0, 12.0),
        },
        component_financial_profiles={
            "Raw Ingredient": {
                "unit_price_min": 5.0,
                "unit_price_max": 80.0,
                "quantity_min": 100.0,
                "quantity_max": 5000.0,
                "line_amount_soft_max": 150000.0,
                "high_value_probability": 0.0,
            },
            "Seasoning": {
                "unit_price_min": 2.0,
                "unit_price_max": 120.0,
                "quantity_min": 20.0,
                "quantity_max": 1500.0,
                "line_amount_soft_max": 100000.0,
                "high_value_probability": 0.0,
            },
            "Edible Oil": {
                "unit_price_min": 5.0,
                "unit_price_max": 90.0,
                "quantity_min": 100.0,
                "quantity_max": 4000.0,
                "line_amount_soft_max": 120000.0,
                "high_value_probability": 0.0,
            },
            "Packaging Film": {
                "unit_price_min": 5.0,
                "unit_price_max": 60.0,
                "quantity_min": 50.0,
                "quantity_max": 3000.0,
                "line_amount_soft_max": 80000.0,
                "high_value_probability": 0.0,
            },
            "Carton": {
                "unit_price_min": 5.0,
                "unit_price_max": 25.0,
                "quantity_min": 200.0,
                "quantity_max": 8000.0,
                "line_amount_soft_max": 75000.0,
                "high_value_probability": 0.0,
            },
            "Label": {
                "unit_price_min": 5.0,
                "unit_price_max": 12.0,
                "quantity_min": 200.0,
                "quantity_max": 10000.0,
                "line_amount_soft_max": 50000.0,
                "high_value_probability": 0.0,
            },
        },
        component_category_aliases={
            "raw ingredients": "Raw Ingredient",
            "raw ingredient": "Raw Ingredient",
            "seasonings & spices": "Seasoning",
            "seasoning": "Seasoning",
            "edible oils": "Edible Oil",
            "edible oil": "Edible Oil",
            "packaging film": "Packaging Film",
            "labels": "Label",
            "label": "Label",
            "cartons": "Carton",
            "carton": "Carton",
        },
        rejection_reasons=(
            "Moisture Out of Spec",
            "Foreign Material Detected",
            "Damaged Packaging",
            "Label Print Defect",
            "Oil Quality Issue",
        ),
        inspection_test_names=(
            "Moisture Check",
            "Foreign Material Check",
            "Seal Integrity Check",
            "Weight Check",
            "Packaging Quality Check",
        ),
        plant_type_names=("Food Processing Plant", "Snack Manufacturing Plant"),
        warehouse_type_names=(
            "Ingredient Warehouse",
            "Packaging Warehouse",
            "Quality Hold Warehouse",
            "Finished Goods Staging Warehouse",
        ),
        supplier_component_relationship_rules=(
            "Ingredient suppliers should be paired with food-grade raw materials.",
            "Packaging suppliers should be paired with film, labels, and carton components.",
        ),
    ),
    production=ProductionProfile(
        product_categories=(
            "Potato Chips",
            "Corn Snacks",
            "Roasted Snacks",
            "Seasoned Snack Mix",
        ),
        product_name_patterns=(
            "Potato Chips",
            "Corn Snacks",
            "Roasted Snacks",
            "Seasoned Snack Mix",
        ),
        work_center_names=(
            "Mixing Station",
            "Frying Line",
            "Roasting Line",
            "Seasoning Tumbler",
            "Cooling Conveyor",
            "Packing Line",
            "Sealing Station",
            "Final Inspection Station",
        ),
        routing_operation_names=(
            "Mixing",
            "Frying",
            "Roasting",
            "Seasoning",
            "Cooling",
            "Packing",
            "Sealing",
            "Final Inspection",
        ),
        product_catalog=(
            {
                "name": "Potato Chips",
                "category": "Potato Chips",
                "product_type": "FinishedGood",
                "uom": "EA",
                "base_cost": 12,
                "base_hours": 1.2,
            },
            {
                "name": "Corn Snacks",
                "category": "Corn Snacks",
                "product_type": "FinishedGood",
                "uom": "EA",
                "base_cost": 10,
                "base_hours": 1.0,
            },
            {
                "name": "Roasted Snacks",
                "category": "Roasted Snacks",
                "product_type": "FinishedGood",
                "uom": "EA",
                "base_cost": 11,
                "base_hours": 1.1,
            },
            {
                "name": "Seasoned Snack Mix",
                "category": "Seasoned Snack Mix",
                "product_type": "FinishedGood",
                "uom": "EA",
                "base_cost": 13,
                "base_hours": 1.3,
            },
        ),
        work_center_catalog=(
            {"name": "Mixing Station", "line_name": "Mixing"},
            {"name": "Frying Line", "line_name": "Frying"},
            {"name": "Roasting Line", "line_name": "Roasting"},
            {"name": "Seasoning Tumbler", "line_name": "Seasoning"},
            {"name": "Cooling Conveyor", "line_name": "Cooling"},
            {"name": "Packing Line", "line_name": "Packing"},
            {"name": "Sealing Station", "line_name": "Sealing"},
            {"name": "Final Inspection Station", "line_name": "Quality"},
        ),
        fallback_components=(
            {"ComponentID": 1, "ComponentName": "Potato Flakes", "UOM": "KG"},
            {"ComponentID": 2, "ComponentName": "Corn Flour", "UOM": "KG"},
            {"ComponentID": 3, "ComponentName": "Edible Oil", "UOM": "Liter"},
            {"ComponentID": 4, "ComponentName": "Masala Seasoning", "UOM": "KG"},
            {"ComponentID": 5, "ComponentName": "Packaging Film Roll", "UOM": "Roll"},
            {"ComponentID": 6, "ComponentName": "Printed Label", "UOM": "Roll"},
            {"ComponentID": 7, "ComponentName": "Corrugated Carton", "UOM": "EA"},
        ),
        fallback_plants=(
            {"PlantID": 1, "PlantName": "Pune Snack Manufacturing Plant"},
        ),
        fallback_warehouses=(
            {"WarehouseID": 1, "PlantID": 1, "WarehouseName": "Pune Ingredient Warehouse"},
        ),
        bom_patterns=(
            "Snack products consume ingredients, oil, seasoning, film, labels, and cartons.",
            "Finished packs combine processed snacks with packaging and label components.",
        ),
        scrap_yield_profiles={
            "Mixing": (0.0, 1.5),
            "Frying": (0.0, 3.0),
            "Roasting": (0.0, 2.5),
            "Packing": (0.0, 1.5),
            "Sealing": (0.0, 1.2),
        },
        quality_defect_codes=(
            "MoistureOutOfSpec",
            "UnderweightPack",
            "SealFailure",
            "SeasoningVariation",
            "ForeignMaterial",
            "PackagingDamage",
        ),
        scrap_reason_codes=(
            "Burnt Batch",
            "Underweight Pack",
            "Seal Failure",
            "Seasoning Variation",
            "Packaging Damage",
        ),
        rework_reason_codes=(
            "Re-season",
            "Re-pack",
            "Re-seal",
            "Weight Adjustment",
            "Packaging Rework",
        ),
        cost_profiles={
            "LaborRatePerHour": (12.0, 35.0),
            "OverheadPct": (4.0, 14.0),
            "ProductionLaborCostPerOperation": (18.0, 45.0),
            "ProductionOverheadPct": (5.0, 16.0),
            "ScrapCostPerUnit": (2.0, 18.0),
            "ReworkCostPerUnit": (1.0, 10.0),
        },
    ),
    shared=SharedProfile(
        countable_uoms=tuple(sorted(INTEGER_QUANTITY_UOMS | {"drum"})),
        measurable_uoms=tuple(sorted(DECIMAL_QUANTITY_UOMS | {"gram"})),
        default_country="India",
        default_currency="INR",
        location_catalog=(
            {"city": "Pune", "state": "Maharashtra", "zip": "411001", "country": "India"},
            {"city": "Indore", "state": "Madhya Pradesh", "zip": "452001", "country": "India"},
            {"city": "Ahmedabad", "state": "Gujarat", "zip": "380001", "country": "India"},
            {"city": "Bengaluru", "state": "Karnataka", "zip": "560001", "country": "India"},
        ),
        date_scope_notes=("Current generated scenarios remain in calendar year 2025.",),
        realism_notes=(
            "Food profile catalog content is used by deterministic Python generation.",
            "LLM output remains planning guidance only.",
        ),
    ),
    sales=SalesProfile(
        customer_types=(
            "Grocery Retailer",
            "Distributor",
            "Foodservice",
            "Convenience Store",
            "E-commerce",
            "Regional Wholesaler",
        ),
        customer_industries=(
            "Food Retail",
            "Grocery Distribution",
            "Foodservice",
            "Convenience Retail",
            "Online Grocery",
            "Wholesale Distribution",
        ),
        customer_name_terms=(
            "FreshMart",
            "DailyBasket",
            "SpiceRoute",
            "SnackHub",
            "QuickGrocery",
            "CityFoods",
            "PantryPlus",
            "RetailKart",
            "FoodLine",
            "GrocerPoint",
        ),
        sales_channels=(
            "DIRECT",
            "DISTRIBUTOR",
            "RETAIL",
            "FOODSERVICE",
            "ONLINE",
            "EXPORT",
        ),
        payment_terms=("Net 15", "Net 30", "Net 45", "Net 60"),
        regions=("West", "South", "North", "East", "Central"),
        carrier_names=(
            "FreshRoute Logistics",
            "SnackLine Freight",
            "Cold Chain Express",
            "Regional Food Transport",
        ),
        payment_methods=("BankTransfer", "UPI", "Cheque", "OnlineTransfer", "Card"),
        tax_rate_pct=5.0,
        freight_amount_range=(250.0, 950.0),
        partial_payment_pct_range=(35.0, 75.0),
        price_margin_pct_range=(20.0, 45.0),
        minimum_order_quantity_range=(1.0, 24.0),
        fallback_price_range=(20.0, 150.0),
    ),
)
