"""Procurement-specific LLM prompt sections."""

from __future__ import annotations

from collections.abc import Sequence

from procurement_data_generator.core.contracts.erd_contract import RelationshipContract
from procurement_data_generator.core.contracts.schema_contract import SchemaContract
from procurement_data_generator.core.modules.contracts import PromptSection


def get_procurement_prompt_sections(
    schema: SchemaContract | None = None,
    relationships: Sequence[RelationshipContract] | None = None,
    scenario: str | None = None,
) -> tuple[PromptSection, ...]:
    return (
        PromptSection(
            section_id="procurement.v2.model",
            title="Procurement v2 Exact Model",
            content=_model_content(),
        ),
        PromptSection(
            section_id="procurement.v2.lifecycle",
            title="Procurement v2 Lifecycle Guidance",
            content=_lifecycle_content(),
        ),
        PromptSection(
            section_id="procurement.v2.status_quality_location",
            title="Procurement v2 Status, Quality, Location, and Currency Rules",
            content=_status_quality_location_content(),
        ),
        PromptSection(
            section_id="procurement.v2.formulas_quantities_validation",
            title="Procurement v2 Formula, Quantity, and Validation Guidance",
            content=_formula_quantity_validation_content(),
        ),
    )


def _model_content() -> str:
    return "\n".join(
        [
            "Use exactly the Procurement v2 metadata model when model_version is v2.",
            "The exact Procurement v2 table list is:",
            "1. SupplierMaster",
            "2. SupplierComponent",
            "3. ComponentMaster",
            "4. Plant",
            "5. Warehouse",
            "6. PurchaseRequisition",
            "7. PurchaseReqLine",
            "8. RFQHeader",
            "9. RFQLine",
            "10. SupplierQuotation",
            "11. SupplierQuotationLn",
            "12. PurchaseOrderHdr",
            "13. PurchaseOrderLine",
            "14. POSchedule",
            "15. ShipmentHdr",
            "16. ShipmentLine",
            "17. GoodsReceiptHeader",
            "18. GoodsReceiptLine",
            "19. IncomingInspection",
            "20. InspectionResult",
            "21. InventoryReceiptDetail",
            "22. InventoryTransaction",
            "23. Inventory",
            "24. SupplierInvoice",
            "25. PaymentTransaction",
            "InventoryReceiptDetail is included in Procurement v2 as the receipt-level traceability table between inspection and inventory posting.",
            "Inventory is included in Procurement v2 as the calculated current stock position table.",
            "InventoryTransaction is included as the detailed inbound StockIn posting table for accepted supplier receipts.",
            "InventoryBalance must not be generated or planned for Procurement v2.",
            "Do not plan PlantMaster or WarehouseMaster. Use Plant and Warehouse.",
        ]
    )


def _lifecycle_content() -> str:
    return "\n".join(
        [
            "Supplier and component setup:",
            "SupplierMaster and ComponentMaster define suppliers and EV components.",
            "SupplierComponent maps suppliers to components they can supply.",
            "RFQ/quotation/PO logic should prefer supplier-component eligible suppliers.",
            "",
            "Procurement lifecycle:",
            "PurchaseRequisition -> PurchaseReqLine -> RFQHeader -> RFQLine -> SupplierQuotation -> SupplierQuotationLn -> PurchaseOrderHdr -> PurchaseOrderLine -> POSchedule -> ShipmentHdr -> ShipmentLine -> GoodsReceiptHeader -> GoodsReceiptLine -> IncomingInspection -> InspectionResult -> InventoryReceiptDetail -> InventoryTransaction -> Inventory -> SupplierInvoice -> PaymentTransaction",
            "",
            "Supporting location lifecycle:",
            "Plant -> Warehouse",
            "Plant -> PurchaseRequisition",
            "Plant/Warehouse -> GoodsReceiptHeader",
            "Plant/Warehouse -> InventoryReceiptDetail",
            "Plant/Warehouse -> InventoryTransaction",
            "Plant/Warehouse -> Inventory",
            "",
            "Important lifecycle rules:",
            "- SupplierQuotation should be generated from RFQHeader.",
            "- SupplierQuotationLn should be generated from RFQLine.",
            "- PurchaseOrderHdr should be created from awarded SupplierQuotation.",
            "- PurchaseOrderLine should be created from awarded SupplierQuotationLn.",
            "- POSchedule should split PurchaseOrderLine delivery quantities.",
            "- ShipmentLine should be generated from POSchedule.",
            "- GoodsReceiptLine should be generated from ShipmentLine.",
            "- IncomingInspection should be generated from GoodsReceiptLine.",
            "- InspectionResult should be generated from IncomingInspection.",
            "- InventoryReceiptDetail must be planned between InspectionResult and InventoryTransaction.",
            "- InventoryReceiptDetail should be generated from InspectionResult, GoodsReceiptLine, PurchaseOrderLine, PurchaseOrderHdr, SupplierMaster, ComponentMaster, Plant, and Warehouse lineage.",
            "- InventoryReceiptDetail should capture expected delivery, actual delivery, stock posted date, ordered/received/accepted quantities, unit price variance, values, order/delivery years, CrossYearDeliveryFlag, delivery delay days, DeliveryStatus, PriceVarianceStatus, and InventoryReceiptStatus.",
            "- InventoryTransaction should be generated from InventoryReceiptDetail, not directly from InspectionResult.",
            "- InventoryTransaction should represent StockIn postings only, with supplier traceability, delivered unit price, and inventory value.",
            "- Inventory should be calculated from InventoryTransaction by ComponentID, PlantID, and WarehouseID.",
            "- SupplierInvoice should be generated after GoodsReceiptHeader.",
            "- PaymentTransaction should be generated after SupplierInvoice.",
        ]
    )


def _status_quality_location_content() -> str:
    return "\n".join(
        [
            "Procurement v2 Hard Rules:",
            "- Do not include InventoryBalance.",
            "- InventoryTransaction.TransactionType must be StockIn for this inbound procurement scenario.",
            "- InventoryReceiptDetail.CrossYearDeliveryFlag is present for traceability but must remain 0 for the current 2025-only scope.",
            "- Use 2025 date range only.",
            "- Use US locations only for Plant, Warehouse, and Supplier location planning.",
            "- Use CurrencyCode = USD for all financial tables.",
            "- For current Procurement v2, POStatus and LineStatus must be Received only because the generated lifecycle is fully received.",
            "- Statuses must be derived from lifecycle facts; do not generate random statuses.",
            "- RejectionReason should be null/blank/Not Applicable when RejectedQuantity = 0.",
            "- RejectionReason should vary when RejectedQuantity > 0.",
            "- LLM must not place cross-table fields in depends_on_columns.",
            "- depends_on_columns must contain same-table columns only.",
            "- Cross-table dependencies must be expressed through date_rules, quantity_rules, formula_rules, or validation_rules.",
            "- Formula text is audit-only; execution uses structured fields.",
            "- For money formulas, use tolerance_type absolute and tolerance_value 0.01 unless the schema says otherwise.",
            "- For quantity formulas, use tolerance_type absolute and tolerance_value 0.0001.",
            "- For percentage formulas, use tolerance_type absolute and tolerance_value 0.01.",
            "- Do not set tolerance_type = none for money/amount reconciliation.",
            "",
            "Lifecycle-Based Status Realism:",
            "The LLM plan should instruct Python to derive statuses from lifecycle facts.",
            "For current Procurement v2, the inbound lifecycle is fully received: POStatus = Received only and LineStatus = Received only.",
            "Statuses must be derived from lifecycle facts.",
            "Do not generate random status values. Statuses should match the full-received lifecycle facts.",
            "- InventoryTransaction supplier and value traceability: fields must come from InventoryReceiptDetail, UnitPrice must equal InventoryReceiptDetail.DeliveredUnitPrice, and InventoryValue must equal TransactionQuantity * UnitPrice.",
            "- InventoryTransaction.UnitPrice = InventoryReceiptDetail.DeliveredUnitPrice.",
            "",
            "Rejection Reason Realism:",
            "- If RejectedQuantity = 0, RejectionReason should be null, blank, or Not Applicable if allowed.",
            "- If RejectedQuantity > 0, RejectionReason must be populated.",
            "- RejectionReason should vary across rejected rows.",
            "- Do not use the same rejection reason for all rows.",
            "- Choose realistic reasons based on the selected industry profile and manufacturing quality context.",
            "",
            "US-Only Location Guidance:",
            "- PlantCountry = USA.",
            "- WarehouseCountry = USA.",
            "- SupplierCountry = USA unless metadata explicitly allows international suppliers. For the v2 fixture, use USA.",
            "- WarehouseCity and WarehouseState must align with Plant/Warehouse logic.",
            "- Warehouses should belong to a Plant.",
            "- Warehouse location should be consistent with its PlantID.",
            "- Do not randomly assign warehouse city/state unrelated to its Plant.",
            "Suggested US plant/warehouse locations: Detroit, Michigan; Austin, Texas; Fremont, California; Phoenix, Arizona; Nashville, Tennessee; Columbus, Ohio; Reno, Nevada; Greenville, South Carolina.",
            "",
            "USD-Only Financial Guidance:",
            "- CurrencyCode must be USD where the column exists.",
            "- SupplierComponent.ContractPrice is in USD.",
            "- SupplierQuotationLn.QuotedUnitPrice and QuotedLineAmount are in USD.",
            "- PurchaseOrderLine.UnitPrice and LineAmount are in USD.",
            "- PurchaseOrderHdr.TotalAmount is in USD.",
            "- SupplierInvoice.InvoiceAmount, TaxAmount, FreightAmount, TotalInvoiceAmount are in USD.",
            "- PaymentTransaction.PaymentAmount is in USD.",
            "- Do not generate other currency codes.",
        ]
    )


def _formula_quantity_validation_content() -> str:
    return "\n".join(
        [
            "Procurement v2 Formula Guidance:",
            "Include only FormulaRule objects that can be expressed using supported structured fields.",
            "- SupplierQuotationLn.QuotedLineAmount: rule_type row_level; operation multiply; input_columns [\"QuotedQuantity\", \"QuotedUnitPrice\"]; target_table SupplierQuotationLn; target_column QuotedLineAmount; tolerance_type absolute; tolerance_value 0.01.",
            "- PurchaseOrderLine.LineAmount: rule_type row_level; operation multiply; input_columns [\"OrderedQuantity\", \"UnitPrice\"]; target_table PurchaseOrderLine; target_column LineAmount; tolerance_type absolute; tolerance_value 0.01.",
            "- PurchaseOrderHdr.TotalAmount: rule_type aggregate; operation sum; source_table PurchaseOrderLine; source_column LineAmount; target_table PurchaseOrderHdr; target_column TotalAmount; relationship_key PurchaseOrderID; tolerance_type absolute; tolerance_value 0.01.",
            "- GoodsReceiptLine.ShortQuantity: rule_type row_level; operation subtract; input_columns [\"ShippedQuantity\", \"ReceivedQuantity\"]; target_table GoodsReceiptLine; target_column ShortQuantity; tolerance_type absolute; tolerance_value 0.0001.",
            "- InspectionResult.RejectedQuantity: rule_type row_level; operation subtract; input_columns [\"InspectedQuantity\", \"AcceptedQuantity\"]; target_table InspectionResult; target_column RejectedQuantity; tolerance_type absolute; tolerance_value 0.0001.",
            "- SupplierInvoice.TotalInvoiceAmount: rule_type row_level; operation add; input_columns [\"InvoiceAmount\", \"TaxAmount\", \"FreightAmount\"]; target_table SupplierInvoice; target_column TotalInvoiceAmount; tolerance_type absolute; tolerance_value 0.01.",
            "- InventoryTransaction.InventoryValue: rule_type row_level; operation multiply; input_columns [\"TransactionQuantity\", \"UnitPrice\"]; target_table InventoryTransaction; target_column InventoryValue; tolerance_type absolute; tolerance_value 0.01.",
            "- Inventory.OnHandQuantity: can be expressed as a validation_rule for now; it must equal SUM(InventoryTransaction.TransactionQuantity) grouped by ComponentID, PlantID, WarehouseID.",
            "- Inventory.OnHandValue: can be expressed as a validation_rule for now; it must equal SUM(InventoryTransaction.InventoryValue) grouped by ComponentID, PlantID, WarehouseID.",
            "- Inventory.AvailableQuantity: can be expressed as a validation_rule for now; it must equal OnHandQuantity - ReservedQuantity.",
            "- Inventory.AvailableValue: can be expressed as a validation_rule for now; it should be derived from AvailableQuantity and average unit cost, where average unit cost is OnHandValue / OnHandQuantity.",
            "- For SupplierInvoice.InvoiceAmount: If current formula schema cannot express received PO value cleanly, include a validation_rule instead of unsafe formula. Do not invent unsupported formula structures.",
            "- Do not set tolerance_type = none for money/amount reconciliation.",
            "",
            "Procurement v2 Date Rule Guidance:",
            "Dates should follow: RequisitionDate <= RFQDate <= QuotationDate <= OrderDate <= ScheduledDeliveryDate <= ShipmentDate <= ReceiptDate <= InspectionDate <= TransactionDate <= InvoiceDate <= PaymentDate.",
            "- All dates must remain within 2025 where metadata date MinValue/MaxValue says 2025.",
            "",
            "Procurement v2 Quantity Rule Guidance:",
            "- RequestedQuantity > 0.",
            "- RFQQuantity should be based on RequestedQuantity.",
            "- QuotedQuantity should be based on RFQQuantity.",
            "- OrderedQuantity should be based on awarded QuotedQuantity.",
            "- ScheduledQuantity should not exceed OrderedQuantity remaining.",
            "- ShippedQuantity should not exceed ScheduledQuantity.",
            "- ReceivedQuantity should not exceed ShippedQuantity.",
            "- DamagedQuantity should not exceed ReceivedQuantity.",
            "- ShortQuantity = ShippedQuantity - ReceivedQuantity.",
            "- InspectedQuantity should be <= ReceivedQuantity.",
            "- AcceptedQuantity + RejectedQuantity = InspectedQuantity.",
            "- InventoryReceiptDetail.AcceptedQuantity = InspectionResult.AcceptedQuantity.",
            "- InventoryTransaction.TransactionQuantity = InventoryReceiptDetail.AcceptedQuantity.",
            "- InventoryTransaction.TransactionType = StockIn.",
            "- InventoryTransaction.UnitPrice = InventoryReceiptDetail.DeliveredUnitPrice.",
            "- InventoryTransaction.InventoryValue = TransactionQuantity * UnitPrice.",
            "- Inventory.OnHandQuantity = SUM(InventoryTransaction.TransactionQuantity) grouped by ComponentID, PlantID, WarehouseID.",
            "- Inventory.OnHandValue = SUM(InventoryTransaction.InventoryValue) grouped by ComponentID, PlantID, WarehouseID.",
            "- Inventory.AvailableQuantity = OnHandQuantity - ReservedQuantity.",
            "- Inventory.AvailableValue is derived from AvailableQuantity and average unit cost.",
            "- PaymentAmount <= SupplierInvoice.TotalInvoiceAmount.",
            "",
            "Procurement v2 Validation Rule Guidance:",
            "- SupplierComponent supplier/component FK consistency.",
            "- RFQLine to requisition line.",
            "- SupplierQuotation to RFQ and Supplier.",
            "- SupplierQuotationLn to SupplierQuotation and RFQLine.",
            "- Awarded quotation to PO.",
            "- PO schedule quantity <= ordered quantity.",
            "- Shipment quantity <= scheduled quantity.",
            "- Receipt quantity <= shipped quantity.",
            "- Inspection accepted + rejected = inspected.",
            "- InventoryReceiptDetail accepted quantity = InspectionResult accepted quantity.",
            "- InventoryTransaction quantity = InventoryReceiptDetail accepted quantity.",
            "- InventoryTransaction SupplierID, GoodsReceiptLineID, PurchaseOrderLineID, ComponentID, PlantID, and WarehouseID must match procurement receipt/PO/inspection lineage.",
            "- InventoryTransaction TransactionType must be StockIn.",
            "- InventoryTransaction UnitPrice equals InventoryReceiptDetail DeliveredUnitPrice.",
            "- InventoryTransaction InventoryValue equals TransactionQuantity times UnitPrice.",
            "- Inventory OnHandQuantity equals grouped InventoryTransaction quantity.",
            "- Inventory OnHandValue equals grouped InventoryTransaction value.",
            "- Inventory AvailableQuantity equals OnHandQuantity minus ReservedQuantity.",
            "- Inventory AvailableValue is derived from AvailableQuantity and average unit cost.",
            "- Invoice after receipt.",
            "- Payment after invoice.",
            "- Payment amount <= invoice total.",
            "- CurrencyCode = USD.",
            "- Country = USA for Plant/Warehouse/Supplier.",
            "- Status diversity where multiple AllowedValues exist.",
            "Use supported validation_rule structures only. Do not invent unsupported schema fields.",
        ]
    )
